version: "3.1"

services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./static:/workspace
    networks:
      vases_network:
  media:
    build:
      context: ./
      dockerfile: ./janus.Dockerfile
    ports:
      - 8088:8088
      - 8188:8188
      - 7088:7088
      - 7089:7089
    networks:
      vases_network:
  redis:
    build:
      context: ./
      dockerfile: ./redis.Dockerfile
    volumes:
      - vases_workspace:/workspace
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    restart: always
    networks:
      vases_network:
  engine:
    build:
      context: ./
      dockerfile: ./engine/engine.Dockerfile
    volumes:
      - vases_workspace:/workspace
    restart: always
    ports:
      - 40000:40000
    environment:
      - PORT=40000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # device_ids:['0']
              count: 1
              capabilities: [gpu]
    image: engine
    container_name: engine
    networks:
      vases_network:
  service:
    build:
      context: ./
      dockerfile: ./service/service.Dockerfile
    volumes:
      - vases_workspace:/workspace
    restart: always
    expose:
      - 8090
    ports:
      - 8090:8090
    image: service
    container_name: service
    networks:
      vases_network:

networks:
  vases_network:

volumes:
  vases_workspace:
