version: "3.1"

services:
  redis:
    build:
      context: ./
      dockerfile: ./redis.Dockerfile
    volumes:
      - saige_workspace:/workspace
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    privileged: true
    restart: always
    networks:
      saige_network:
  python-service:
    build:
      context: ./
      dockerfile: ./python.Dockerfile
    volumes:
      - saige_workspace:/workspace
    restart: always
    privileged: true
    ports:
      - 40000:40000
    environment:
      - PORT=40000
    image: python-service
    container_name: python-service
    networks:
      saige_network:

networks:
  saige_network:

volumes:
  saige_workspace:
    external: true
